### ISSUE TITLE
Restart?

### ISSUE THREAD

**Issue by JiveyGuy** [JiveyGuy/open_cyber_center#7]
Should we just restart from scratch considering all we know now and how many mistakes we made along the way?

**Comment by JiveyGuy** [comment]
@cmuel10 What do you think?

**Comment by cmuel10** [comment]
> 

Yes, I would be down to restart and see if we can come up with a better end product if you would like to. Also - I would like to do it on my personal github if possible @courtmuel on github. Let me know!

**Comment by JiveyGuy** [comment]
Awesome! 

I saw your discord message but I am having trouble replying through my company firewall. How about we make some sort of organization for it with a name like  _Open Gaming_ and we can be listed on the people page like https://github.com/tauri-apps has done?

**Comment by courtmuel** [comment]
Yup that sounds good to me! Would be a good thing to have on our resumes and would be good to get featured on that page I feel. I can try to brainstorm some good names for the project and see what I can come up with. Would we wanna switch over to Javascript or stick with Typescript?

**Comment by JiveyGuy** [comment]
> Yup that sounds good to me! Would be a good thing to have on our resumes and would be good to get featured on that page I feel. I can try to brainstorm some good names for the project and see what I can come up with. Would we wanna switch over to Javascript or stick with Typescript?

I think we swap over to JS. And we utilize the rust backend A LOT more.

**Comment by courtmuel** [comment]
Sorry about the late reply the last 2 weeks have been all over the place. I don't know if you have already started on getting the ball rolling for this - but I can attempt to do so if not. I can make a new repository for us if you would like.

**Comment by JiveyGuy** [comment]
> Sorry about the late reply the last 2 weeks have been all over the place. I don't know if you have already started on getting the ball rolling for this - but I can attempt to do so if not. I can make a new repository for us if you would like.

No worries! Yeah I can start working on it, I think since you want to dedicate lots of time to this you should own the organization so go to: [Make new organization free](https://github.com/account/organizations/new?plan=free&ref_cta=Create%2520a%2520free%2520organization&ref_loc=cards&ref_page=%2Forganizations%2Fplan) and make it. I think any name like "Open Game Cafe Foundation" or something similar will be good. After that invite me to the organization and we can come up with a game plan.

**Comment by courtmuel** [comment]
I went ahead and made the organization - I went with "Open Game Cafe Foundation" like you previously mentioned but also came up with the following, some are very similar and some are a bit different let me know what your favorite is. I have sent you an invite to the org! @JiveyGuy 

- Level Up Lounge / Level Up Foundation 
- Game On Cafe
- Open Arcade Collective 
- Game Matrix Foundation 
- Game Haven Hub 
- Playtopia Cafe

**Comment by JiveyGuy** [comment]
I think your choice is great, invite me to be a member when you can! 

I had a few ideas on how to proceed but I think step one is to make our main repo which should be Open Cyber Center and discuss there on issues.

**Comment by courtmuel** [comment]
You should have a invite to the organization. Let me know if you get it.

**Comment by JiveyGuy** [comment]
Go it, I will make an occ repo and make an issue where are can move this convo.

**Comment by JiveyGuy** [comment]
Let's move here. 

https://github.com/Open-Game-Cafe-Foundation/open_cyber_center/issues/1
